filebeat.prospectors:
-
  paths:
  - /var/log/*.log
  document_type: lstest-logs
name: lstest
logging.files:
  rotateeverybytes: 10485760
output.logstash:
  hosts: [ "{{LOGSTASH_HOST}}:{{LOGSTASH_PORT}}" ]

